// Code generated by gobind. DO NOT EDIT.

// Package main is an autogenerated binder stub for package ollama.
//
//	autogenerated by gobind -lang=go github.com/ollama/ollama/app/cmd/android/ollama
package main

/*
#include <stdlib.h>
#include <stdint.h>
#include "seq.h"
#include "ollama.h"

*/
import "C"

import (
	"github.com/ollama/ollama/app/cmd/android/ollama"
	_seq "golang.org/x/mobile/bind/seq"
)

// suppress the error if seq ends up unused
var _ = _seq.FromRefNum

//export proxyollama_Result_Port_Set
func proxyollama_Result_Port_Set(refnum C.int32_t, v C.nint) {
	ref := _seq.FromRefNum(int32(refnum))
	_v := int(v)
	ref.Get().(*ollama.Result).Port = _v
}

//export proxyollama_Result_Port_Get
func proxyollama_Result_Port_Get(refnum C.int32_t) C.nint {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*ollama.Result).Port
	_v := C.nint(v)
	return _v
}

//export proxyollama_Result_Token_Set
func proxyollama_Result_Token_Set(refnum C.int32_t, v C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	_v := decodeString(v)
	ref.Get().(*ollama.Result).Token = _v
}

//export proxyollama_Result_Token_Get
func proxyollama_Result_Token_Get(refnum C.int32_t) C.nstring {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*ollama.Result).Token
	_v := encodeString(v)
	return _v
}

//export new_ollama_Result
func new_ollama_Result() C.int32_t {
	return C.int32_t(_seq.ToRefNum(new(ollama.Result)))
}

//export proxyollama__Start
func proxyollama__Start(param_dataDir C.nstring) (C.int32_t, C.int32_t) {
	_param_dataDir := decodeString(param_dataDir)
	res_0, res_1 := ollama.Start(_param_dataDir)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	var _res_1 C.int32_t = _seq.NullRefNum
	if res_1 != nil {
		_res_1 = C.int32_t(_seq.ToRefNum(res_1))
	}
	return _res_0, _res_1
}

//export proxyollama__Stop
func proxyollama__Stop() {
	ollama.Stop()
}
