// Code generated by gobind. DO NOT EDIT.

// JNI function headers for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java github.com/ollama/ollama/app/cmd/android/ollama

#ifndef __Ollama_H__
#define __Ollama_H__

#include <jni.h>

extern jclass proxy_class_ollama_Result;
extern jmethodID proxy_class_ollama_Result_cons;
#endif
