// Code generated by gobind. DO NOT EDIT.

// JNI functions for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java github.com/ollama/ollama/app/cmd/android/ollama

#include <android/log.h>
#include <stdint.h>
#include "seq.h"
#include "_cgo_export.h"
#include "ollama.h"

jclass proxy_class_ollama_Result;
jmethodID proxy_class_ollama_Result_cons;

JNIEXPORT void JNICALL
Java_ollama_Ollama__1init(JNIEnv *env, jclass _unused) {
	jclass clazz;
	clazz = (*env)->FindClass(env, "ollama/Result");
	proxy_class_ollama_Result = (*env)->NewGlobalRef(env, clazz);
	proxy_class_ollama_Result_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
}

JNIEXPORT jobject JNICALL
Java_ollama_Ollama_start(JNIEnv* env, jclass _clazz, jstring dataDir) {
	nstring _dataDir = go_seq_from_java_string(env, dataDir);
	struct proxyollama__Start_return res = proxyollama__Start(_dataDir);
	jobject _r0 = go_seq_from_refnum(env, res.r0, proxy_class_ollama_Result, proxy_class_ollama_Result_cons);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT void JNICALL
Java_ollama_Ollama_stop(JNIEnv* env, jclass _clazz) {
	proxyollama__Stop();
}

JNIEXPORT jint JNICALL
Java_ollama_Result__1_1New(JNIEnv *env, jclass clazz) {
	return new_ollama_Result();
}

JNIEXPORT void JNICALL
Java_ollama_Result_setPort(JNIEnv *env, jobject this, jlong v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nint _v = (nint)v;
	proxyollama_Result_Port_Set(o, _v);
}

JNIEXPORT jlong JNICALL
Java_ollama_Result_getPort(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nint r0 = proxyollama_Result_Port_Get(o);
	jlong _r0 = (jlong)r0;
	return _r0;
}

JNIEXPORT void JNICALL
Java_ollama_Result_setToken(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxyollama_Result_Token_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_ollama_Result_getToken(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxyollama_Result_Token_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

