// Code generated by gobind. DO NOT EDIT.

// Java class ollama.Ollama is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/ollama/ollama/app/cmd/android/ollama
package ollama;

import go.Seq;

public abstract class Ollama {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Ollama() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	/**
	 * Start initialises the Go HTTP server on a random port.
	dataDir should be context.filesDir on Android.
	Returns Result with port and auth token.
	 */
	public static native Result start(String dataDir) throws Exception;
	/**
	 * Stop gracefully shuts down the HTTP server.
	 */
	public static native void stop();
}
